name: Build/Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run test

      - uses: blacha/hyperfine-action@v1
