name: Build/Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: blacha/yarn-typescript-action@v1
      
      - name: Create github release
        if: startsWith(github.ref, 'refs/tags/v')
        run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish NPM
        if: startsWith(github.ref, 'refs/tags/v')
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - uses: blacha/hyperfine-action@v1
